
#server.host = 192.168.1.123
server.port = 3307


##database configuration:mysql localhost
#server.host = localhost
#server.port = 8081
#spring.datasource.url=jdbc:mysql://localhost:3306/myhiber
#spring.datasource.username=root
#spring.datasource.password=root

spring.profiles.active=${ENV:dev}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

##Security Authantication
#logging.level.org.springframework.security=debug
#spring.security.user.name=admin
#spring.security.user.password=admin@123$
#spring.security.user.roles=Admin


#------------------------------------------------------------------------------------------------------------------------------------------------------#

#https://www.youtube.com/watch?v=_thI-4AF7M8&t=31s
#https://www.youtube.com/watch?v=ZkCokUMqy9c
#https://www.youtube.com/watch?v=WH_d9Tw4CPs&t=472s


#/* 15 may - june - july */

#This is the Steps to follow
#1.Create a new repository on GitHub. 
#2.Right-click on the project and choose ‘Show in Local Terminal’ - Git Bash
#3.(if you don’t see Git Bash, then install it)
#4.Initialize the local directory as a Git repository.
#
#    $ git init
#
#5.Add the files in your new local repository. This stages them for the first commit.
#
#    $ git add .
#
#6.Adds the files in the local repository and stages them for commit.
#7.Commit the files that you've staged in your local repository.
#
#    $ git commit -m "First commit"
#
#Commits the tracked changes and prepares them to be pushed to a remote repository. 
#8.Go and copy your remote repository url (it ends in .git)
#9.In the Command prompt, add the remote repository url
# 
#    $ git remote add origin https://github.com/Vishal007M/Allegient_invoice_Api.git
#    $ git remote -v
#
#Verifies the new remote URL
#10.Push the changes in your local repository to GitHub.
#
#    $ git push origin master
#
#Pushes the changes in your local repository up to the remote repository 


