#database configuration:mysql
spring.datasource.url=jdbc:mysql://containers-us-west-89.railway.app:6985/railway
spring.datasource.username=root
spring.datasource.password=sVTmGsk3c5b32OZvXsQx


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false